version: '3.3'

services:
   db:
     container_name: zegarmistrz_mysql
     image: mysql:8.0
     volumes:
       - /var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_DATABASE: ps
       MYSQL_USER: ps
       MYSQL_PASSWORD: ps
     networks:
       - zegarmistrz-net

   prestashop:
     depends_on:
       - db
     container_name: zegarmistrz_ps
     image: prestashop/prestashop:1.7
     ports:
       - "35111:80"
     restart: always
     environment:
       PS_INSTALL_AUTO: 0
       PS_ERASE_DB: 0
       DB_SERVER: db
       DB_USER: ps
       DB_PASSWD: ps
       DB_NAME: ps
       PS_DEV_MODE: 0
       PS_DOMAIN: localhost:8011
       PS_FOLDER_ADMIN: admin123
       PS_FOLDER_INSTALL: install123
     volumes:
       - /var/www/html
       - ./my_module:/var/www/html/modules/my_module
       - ./my_theme:/var/www/html/themes/my_theme
       - ./override:/var/www/html/override
     networks:
       - zegarmistrz-net

networks:
  zegarmistrz-net:
    name: zegarmistrz-net


