version: '3.3'

services:
   db:
     image: mysql:8.0
     volumes:
       - /var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: admin
       MYSQL_DATABASE: ps
       MYSQL_USER: ps
       MYSQL_PASSWORD: ps

   prestashop:
     depends_on:
       - db
     image: prestashop/prestashop:1.7.8.0
     ports:
       - "8011:80"
     restart: always
     environment:
       PS_INSTALL_AUTO: 0
       PS_ERASE_DB: 0
       DB_SERVER: db
       DB_USER: ps
       DB_PASSWD: ps
       DB_NAME: ps
       PS_DEV_MODE: 0
       PS_DOMAIN: localhost:8011
       PS_FOLDER_ADMIN: admin123
       PS_FOLDER_INSTALL: install123
     volumes:
       - /var/www/html
       - ./my_module:/var/www/html/modules/my_module
       - ./my_theme:/var/www/html/themes/my_theme
       - ./override:/var/www/html/override
